apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-controller.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mock-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mock-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
