replicaCount: 1

image:
  repository: host.docker.internal:5000/mock-controller/alpine
  # Alternatives: 3.18, 3.17, 3.16, latest, edge
  tag: "3.16"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534

metrics:
  port: 8080

healthProbe:
  port: 8081

leaderElection:
  enabled: true
